INSERT INTO
    "public"."activity_packages" (
        "id",
        "activity_id",
        "name",
        "description",
        "price_per_person",
        "min_participants",
        "max_participants",
        "start_time",
        "end_time",
        "host_id",
        "address",
        "image_url"
    )
VALUES
    (
        '1',
        '1',
        'Group Package',
        'Snorkeling tour with other groups, includes gear and lunch.',
        '650000.00',
        '4',
        '15',
        '09:00:00',
        '16:00:00',
        '1',
        'Pelabuhan Waisai, Raja Ampat, Papua Barat',
        'https://www.komodoluxury.com/wp-content/uploads/2024/02/21e0c704-187b-488c-8e8c-038c2fbf7114_11zon.webp'
    ),
    (
        '2',
        '1',
        'Private Package',
        'Exclusive tour with a private boat and a dedicated guide for your group.',
        '1200000.00',
        '2',
        '6',
        '09:00:00',
        '16:00:00',
        '3',
        'Pelabuhan Waisai, Raja Ampat, Papua Barat',
        'https://www.komodoluxury.com/wp-content/uploads/2024/03/IMG_4621_11zon_11zon.webp'
    ),
    (
        '3',
        '2',
        'Public Trip',
        'Snorkeling at the 3 Gili Islands (Trawangan, Meno, Air) with a glass bottom boat.',
        '150000.00',
        '1',
        '20',
        '10:00:00',
        '15:00:00',
        '4',
        'Public Harbour, Gili Trawangan, Lombok Utara, NTB',
        'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/60/e9/51/underwater-statue.jpg?w=1200&h=-1&s=1'
    ),
    (
        '4',
        '2',
        'Private Charter',
        'Rent a private boat for a full day to snorkel at your own pace at the best spots.',
        '800000.00',
        '1',
        '8',
        '09:30:00',
        '16:00:00',
        '1',
        'Public Harbour, Gili Trawangan, Lombok Utara, NTB',
        'https://www.komodoluxury.com/wp-content/uploads/2024/02/21e0c704-187b-488c-8e8c-038c2fbf7114_11zon.webp'
    ),
    (
        '5',
        '3',
        '1 Day Tour',
        'Includes boat, snorkeling gear, grilled fish lunch, and documentation.',
        '250000.00',
        '5',
        '15',
        '08:30:00',
        '16:30:00',
        '4',
        'Pelabuhan Kartini, Jepara, Jawa Tengah (Meeting point for ferry crossing)',
        'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/07/c3/f7/53/sea-adventure-excursions.jpg?w=1200&h=900&s=1'
    ),
    (
        '6',
        '3',
        '2-Day 1-Night Package',
        'Includes accommodation, 2 days of sea tours, and all facilities.',
        '750000.00',
        '4',
        '12',
        '08:00:00',
        '17:00:00',
        '4',
        'Pelabuhan Kartini, Jepara, Jawa Tengah (Meeting point for ferry crossing)',
        'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/07/c3/f7/53/sea-adventure-excursions.jpg?w=1200&h=900&s=1'
    ),
    (
        '7',
        '4',
        'Bunaken Snorkeling Package',
        'Explore 2 of the best spots in Bunaken National Park.',
        '450000.00',
        '2',
        '10',
        '09:00:00',
        '15:00:00',
        '1',
        'Pelabuhan Calaca, Manado, Sulawesi Utara',
        'https://torch.id/cdn/shop/articles/Artikel_172_-_Preview.webp?v=1713774282'
    ),
    (
        '8',
        '4',
        'Snorkeling & Photography',
        'A special package with a professional underwater photographer.',
        '900000.00',
        '2',
        '6',
        '09:00:00',
        '15:00:00',
        '3',
        'Pelabuhan Calaca, Manado, Sulawesi Utara',
        'https://res.cloudinary.com/manawa/image/upload/f_auto,c_limit,w_3840,q_auto/articles/most-beautiful-spots-for-your-first-scuba-dive/61396758347_kwukov'
    ),
    (
        '9',
        '5',
        'Manta Ray Trip',
        'Focuses on snorkeling at Manta Point and Manta Bay.',
        '350000.00',
        '2',
        '12',
        '08:30:00',
        '13:00:00',
        '3',
        'Pelabuhan Toyapakeh, Nusa Penida, Bali',
        'https://picsum.photos/seed/pkg-manta-trip/800/600'
    ),
    (
        '10',
        '5',
        'West Penida Snorkeling Combo',
        'Snorkeling at Manta Bay, Gamat Bay, and Crystal Bay.',
        '450000.00',
        '2',
        '12',
        '08:30:00',
        '16:00:00',
        '1',
        'Pelabuhan Toyapakeh, Nusa Penida, Bali',
        'https://picsum.photos/seed/pkg-penida-combo/800/600'
    ),
    (
        '11',
        '6',
        'One Day Trip',
        'Depart in the morning, return in the evening from Muara Angke, all facilities included.',
        '350000.00',
        '10',
        '30',
        '07:00:00',
        '18:00:00',
        '4',
        'Dermaga Marina Ancol atau Pelabuhan Muara Angke, Jakarta Utara',
        'https://picsum.photos/seed/pkg-oneday-pari/800/600'
    ),
    (
        '12',
        '6',
        'Overnight Package',
        'A 2D1N package including an air-conditioned homestay and a BBQ night.',
        '600000.00',
        '8',
        '20',
        '07:00:00',
        '15:00:00',
        '4',
        'Dermaga Marina Ancol atau Pelabuhan Muara Angke, Jakarta Utara',
        'https://picsum.photos/seed/pkg-overnight-pari/800/600'
    ),
    (
        '13',
        '7',
        'Speedboat Trip',
        'A fast tour by speedboat visiting Padar Island, Komodo Island, and Pink Beach.',
        '1300000.00',
        '1',
        '12',
        '06:00:00',
        '17:00:00',
        '1',
        'Pelabuhan Labuan Bajo, Manggarai Barat, NTT',
        'https://picsum.photos/seed/pkg-speedboat-komodo/800/600'
    ),
    (
        '14',
        '7',
        'Phinisi Slow Sailing',
        'A relaxed tour on a phinisi boat, allowing more time for snorkeling.',
        '950000.00',
        '4',
        '15',
        '07:00:00',
        '17:00:00',
        '3',
        'Pelabuhan Labuan Bajo, Manggarai Barat, NTT',
        'https://picsum.photos/seed/pkg-phinisi-komodo/800/600'
    ),
    (
        '15',
        '8',
        'Daily Dive Trip (3 Dives)',
        'Dive at 3 different spots in one day, for certified divers.',
        '1800000.00',
        '1',
        '8',
        '07:30:00',
        '16:30:00',
        '3',
        'Pelabuhan Labuan Bajo, Manggarai Barat, NTT',
        'https://picsum.photos/seed/pkg-daily-dive-komodo/800/600'
    ),
    (
        '16',
        '8',
        'Komodo Liveaboard (3D2N)',
        'The ultimate diving experience by staying on the boat.',
        '7500000.00',
        '4',
        '12',
        '10:00:00',
        '15:00:00',
        '3',
        'Pelabuhan Labuan Bajo, Manggarai Barat, NTT',
        'https://picsum.photos/seed/pkg-liveaboard-komodo/800/600'
    ),
    (
        '17',
        '9',
        'Resort Dive Package',
        'A dive package including a stay at a Wakatobi dive resort.',
        '4000000.00',
        '2',
        '6',
        '08:00:00',
        '16:00:00',
        '1',
        'Bandara Matahora atau Pelabuhan Wanci, Pulau Wangi-Wangi, Wakatobi',
        'https://picsum.photos/seed/pkg-resort-wakatobi/800/600'
    ),
    (
        '18',
        '9',
        'Fun Dives',
        'For certified divers, 2 dives per day.',
        '1500000.00',
        '1',
        '8',
        '08:30:00',
        '14:00:00',
        '3',
        'Bandara Matahora atau Pelabuhan Wanci, Pulau Wangi-Wangi, Wakatobi',
        'https://picsum.photos/seed/pkg-fun-dive-wakatobi/800/600'
    ),
    (
        '19',
        '10',
        'Liberty Wreck Shore Dive',
        '2 shore dives at the USAT Liberty shipwreck.',
        '900000.00',
        '1',
        '6',
        '09:00:00',
        '13:00:00',
        '1',
        'Meeting Point at Liberty Dive Resort, Tulamben, Karangasem, Bali',
        'https://picsum.photos/seed/pkg-wreck-dive/800/600'
    ),
    (
        '20',
        '10',
        'Night Dive',
        'Experience the shipwreck differently by diving at night.',
        '650000.00',
        '2',
        '6',
        '18:30:00',
        '20:30:00',
        '1',
        'Meeting Point at Liberty Dive Resort, Tulamben, Karangasem, Bali',
        'https://picsum.photos/seed/pkg-night-dive/800/600'
    ),
    (
        '21',
        '11',
        'Weh Island Fun Dives',
        'Dive around Rubiah Island, rich with marine life.',
        '500000.00',
        '1',
        '8',
        '09:30:00',
        '15:00:00',
        '3',
        'Pelabuhan Balohan, Sabang, Pulau Weh, Aceh',
        'https://picsum.photos/seed/pkg-fun-dive-weh/800/600'
    ),
    (
        '22',
        '11',
        'Deep Dive Special',
        'Explore the Canyon and other deep dive spots.',
        '700000.00',
        '2',
        '6',
        '10:00:00',
        '13:00:00',
        '3',
        'Pelabuhan Balohan, Sabang, Pulau Weh, Aceh',
        'https://picsum.photos/seed/pkg-deep-dive-weh/800/600'
    ),
    (
        '23',
        '12',
        'Standard Cabin',
        'A 4D3N Liveaboard with a standard fan-cooled cabin.',
        '9500000.00',
        '6',
        '12',
        '11:00:00',
        '14:00:00',
        '1',
        'Pelabuhan Waisai, Raja Ampat, Papua Barat',
        'https://picsum.photos/seed/pkg-liveaboard-standard/800/600'
    ),
    (
        '24',
        '12',
        'Master Cabin AC',
        'A 4D3N Liveaboard with an air-conditioned master cabin and private bathroom.',
        '15000000.00',
        '2',
        '8',
        '11:00:00',
        '14:00:00',
        '3',
        'Pelabuhan Waisai, Raja Ampat, Papua Barat',
        'https://picsum.photos/seed/pkg-liveaboard-master/800/600'
    ),
    (
        '25',
        '13',
        'PADI AOW Course',
        'A 2-3 day course to get your Advanced Open Water certification.',
        '4500000.00',
        '1',
        '4',
        '09:00:00',
        '16:00:00',
        '1',
        'Public Harbour, Gili Trawangan, Lombok Utara, NTB',
        'https://picsum.photos/seed/pkg-padi-course/800/600'
    ),
    (
        '26',
        '13',
        'SSI AOW Course',
        'An Advanced course option from SSI, usually slightly cheaper.',
        '4200000.00',
        '1',
        '4',
        '09:00:00',
        '16:00:00',
        '3',
        'Public Harbour, Gili Trawangan, Lombok Utara, NTB',
        'https://picsum.photos/seed/pkg-ssi-course/800/600'
    ),
    (
        '27',
        '14',
        'Boat Dive (2 Dives)',
        'Dive at 2 of the best wall diving spots like Lekuan I and II.',
        '1100000.00',
        '1',
        '8',
        '08:30:00',
        '14:00:00',
        '1',
        'Pelabuhan Calaca, Manado, Sulawesi Utara',
        'https://picsum.photos/seed/pkg-wall-dive/800/600'
    ),
    (
        '28',
        '14',
        'Photography Dive',
        'A slower-paced dive focused on getting great shots for photographers.',
        '1500000.00',
        '1',
        '4',
        '08:30:00',
        '15:00:00',
        '3',
        'Pelabuhan Calaca, Manado, Sulawesi Utara',
        'https://picsum.photos/seed/pkg-photo-dive-wall/800/600'
    ),
    (
        '29',
        '15',
        'Midnight Tour',
        'Depart at midnight from Malang/Surabaya, includes jeep and entrance tickets.',
        '550000.00',
        '2',
        '6',
        '00:30:00',
        '12:00:00',
        '2',
        'Area Parkir Jeep Cemoro Lawang, Ngadisari, Probolinggo, Jawa Timur',
        'https://picsum.photos/seed/pkg-bromo-jeep-group/800/600'
    ),
    (
        '30',
        '15',
        'Private Jeep Charter',
        'Rent a full jeep for your group for more flexibility.',
        '1800000.00',
        '1',
        '6',
        '01:00:00',
        '11:00:00',
        '5',
        'Area Parkir Jeep Cemoro Lawang, Ngadisari, Probolinggo, Jawa Timur',
        'https://picsum.photos/seed/pkg-bromo-jeep-private/800/600'
    ),
    (
        '31',
        '16',
        'Half Day Tour',
        'Visit the Tegalalang rice terraces and a coffee plantation.',
        '300000.00',
        '2',
        '6',
        '09:00:00',
        '14:00:00',
        '2',
        'Meeting Point at Ubud Palace, Jl. Raya Ubud No.8, Ubud, Gianyar, Bali',
        'https://picsum.photos/seed/pkg-ubud-half/800/600'
    ),
    (
        '32',
        '16',
        'Full Day Ubud Explorer',
        'Also includes the Monkey Forest, Tirta Empul temple, and lunch.',
        '600000.00',
        '2',
        '6',
        '09:00:00',
        '17:00:00',
        '2',
        'Meeting Point at Ubud Palace, Jl. Raya Ubud No.8, Ubud, Gianyar, Bali',
        'https://picsum.photos/seed/pkg-ubud-full/800/600'
    ),
    (
        '33',
        '17',
        'Sunrise Borobudur & Prambanan',
        'Witness the sunrise at Borobudur then continue to Prambanan temple.',
        '750000.00',
        '2',
        '5',
        '04:00:00',
        '15:00:00',
        '5',
        'Titik Nol Kilometer Yogyakarta (Near Central Post Office), Yogyakarta',
        'https://picsum.photos/seed/pkg-temple-sunrise/800/600'
    ),
    (
        '34',
        '17',
        'Regular Temple Tour',
        'A relaxed tour visiting both temples during the daytime.',
        '450000.00',
        '2',
        '5',
        '08:00:00',
        '16:00:00',
        '2',
        'Titik Nol Kilometer Yogyakarta (Near Central Post Office), Yogyakarta',
        'https://picsum.photos/seed/pkg-temple-regular/800/600'
    ),
    (
        '35',
        '18',
        'Blue Fire Tour',
        'Includes guide, gas mask, and transportation from Banyuwangi.',
        '400000.00',
        '2',
        '10',
        '00:00:00',
        '09:00:00',
        '5',
        'Pos Paltuding (Gerbang Masuk Kawah Ijen), Banyuwangi, Jawa Timur',
        'https://picsum.photos/seed/pkg-ijen-blue-fire/800/600'
    ),
    (
        '36',
        '18',
        'All-in from Surabaya',
        'A complete 2D1N package including transport from Surabaya and accommodation.',
        '1500000.00',
        '4',
        '8',
        '19:00:00',
        '12:00:00',
        '5',
        'Pos Paltuding (Gerbang Masuk Kawah Ijen), Banyuwangi, Jawa Timur',
        'https://picsum.photos/seed/pkg-ijen-all-in/800/600'
    ),
    (
        '37',
        '19',
        'Rinca Island Trek',
        'A short trek (1 hour) on Rinca Island.',
        '250000.00',
        '2',
        '8',
        '09:00:00',
        '12:00:00',
        '2',
        'Pelabuhan Labuan Bajo, Manggarai Barat, NTT',
        'https://picsum.photos/seed/pkg-komodo-short-trek/800/600'
    ),
    (
        '38',
        '19',
        'Komodo Island Medium Trek',
        'A longer trek (2-3 hours) on Komodo Island for a greater chance of encountering wildlife.',
        '400000.00',
        '2',
        '8',
        '08:30:00',
        '13:00:00',
        '5',
        'Pelabuhan Labuan Bajo, Manggarai Barat, NTT',
        'https://picsum.photos/seed/pkg-komodo-long-trek/800/600'
    ),
    (
        '39',
        '20',
        'City Tour',
        'A 6-hour tour visiting the Sultans Palace, Water Castle, and a Batik center.',
        '350000.00',
        '2',
        '5',
        '09:00:00',
        '15:00:00',
        '2',
        'Titik Nol Kilometer Yogyakarta (Near Central Post Office), Yogyakarta',
        'https://picsum.photos/seed/pkg-yogya-city/800/600'
    ),
    (
        '40',
        '20',
        'Street Food Night Tour',
        'Explore the legendary nightlife and street food of Yogyakarta.',
        '250000.00',
        '2',
        '8',
        '18:00:00',
        '22:00:00',
        '2',
        'Titik Nol Kilometer Yogyakarta (Near Central Post Office), Yogyakarta',
        'https://picsum.photos/seed/pkg-yogya-food/800/600'
    ),
    (
        '41',
        '1',
        'Family Fun Snorkel',
        'A shorter, relaxed snorkeling trip perfect for families with children, focusing on calm and shallow spots.',
        '500000.00',
        '2',
        '8',
        '10:00:00',
        '14:00:00',
        '4',
        'Pelabuhan Waisai, Raja Ampat, Papua Barat',
        'https://www.komodoluxury.com/wp-content/uploads/2024/02/21e0c704-187b-488c-8e8c-038c2fbf7114_11zon.webp'
    ),
    (
        '42',
        '2',
        'Sunset Snorkel & BBQ',
        'An afternoon snorkeling trip to Turtle Point, followed by a fresh seafood BBQ on the beach as the sun sets.',
        '350000.00',
        '4',
        '12',
        '15:00:00',
        '19:00:00',
        '4',
        'Public Harbour, Gili Trawangan, Lombok Utara, NTB',
        'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/60/e9/51/underwater-statue.jpg?w=1200&h=-1&s=1'
    ),
    (
        '43',
        '2',
        'Gili Meno Underwater Statues Trip',
        'A dedicated trip to the famous underwater statues at Gili Meno for incredible photo opportunities.',
        '200000.00',
        '2',
        '15',
        '11:00:00',
        '14:00:00',
        '1',
        'Public Harbour, Gili Trawangan, Lombok Utara, NTB',
        'https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/0b/ea/a8/85.jpg'
    ),
    (
        '44',
        '3',
        'Island Camping & Snorkel (3D2N)',
        'An adventurous 3-day, 2-night trip including island hopping, snorkeling, and camping on a remote island.',
        '1200000.00',
        '6',
        '12',
        '08:00:00',
        '16:00:00',
        '5',
        'Pelabuhan Kartini, Jepara, Jawa Tengah (Meeting point for ferry crossing)',
        'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/07/c3/f7/53/sea-adventure-excursions.jpg?w=1200&h=900&s=1'
    ),
    (
        '45',
        '4',
        'Discovery Scuba Dive',
        'Not certified? No problem. Try scuba diving for the first time with a professional PADI instructor in the calm waters of Bunaken.',
        '950000.00',
        '1',
        '4',
        '10:00:00',
        '13:00:00',
        '3',
        'Pelabuhan Calaca, Manado, Sulawesi Utara',
        'https://res.cloudinary.com/manawa/image/upload/f_auto,c_limit,w_3840,q_auto/articles/most-beautiful-spots-for-your-first-scuba-dive/61396758347_kwukov'
    ),
    (
        '46',
        '5',
        'East & West Penida Full Day Tour',
        'A comprehensive tour covering the best of both sides of Nusa Penida, including Kelingking Beach, Diamond Beach, and snorkeling spots.',
        '850000.00',
        '2',
        '6',
        '08:00:00',
        '17:00:00',
        '4',
        'Pelabuhan Toyapakeh, Nusa Penida, Bali',
        'https://picsum.photos/seed/pkg-east-west-penida/800/600'
    ),
    (
        '47',
        '8',
        'PADI Open Water Course',
        'Get your PADI Open Water certification in 3-4 days in the world-class diving environment of Komodo National Park.',
        '6500000.00',
        '1',
        '4',
        '08:00:00',
        '17:00:00',
        '3',
        'Pelabuhan Labuan Bajo, Manggarai Barat, NTT',
        'https://picsum.photos/seed/pkg-padi-owc/800/600'
    ),
    (
        '48',
        '10',
        'Sunrise Wreck Dive',
        'Be the first in the water with an early morning dive at the Liberty Wreck, enjoying serene conditions and seeing nocturnal creatures retreat.',
        '700000.00',
        '2',
        '6',
        '06:00:00',
        '08:00:00',
        '3',
        'Meeting Point at Liberty Dive Resort, Tulamben, Karangasem, Bali',
        'https://picsum.photos/seed/pkg-sunrise-wreck/800/600'
    ),
    (
        '49',
        '12',
        'Budget Liveaboard (Dorm)',
        'Explore Raja Ampat on a budget-friendly liveaboard with shared dormitory-style cabins.',
        '8000000.00',
        '8',
        '16',
        '11:00:00',
        '14:00:00',
        '1',
        'Pelabuhan Waisai, Raja Ampat, Papua Barat',
        'https://picsum.photos/seed/pkg-liveaboard-dorm/800/600'
    ),
    (
        '50',
        '12',
        'Luxury Liveaboard (Private Suite)',
        'Experience Raja Ampat in ultimate comfort on a luxury phinisi with a private suite and gourmet meals.',
        '25000000.00',
        '2',
        '6',
        '11:00:00',
        '14:00:00',
        '1',
        'Pelabuhan Waisai, Raja Ampat, Papua Barat',
        'https://picsum.photos/seed/pkg-liveaboard-luxury/800/600'
    ),
    (
        '51',
        '15',
        'Bromo Milky Way & Sunrise Tour',
        'A special tour for photographers, starting earlier to capture the Milky Way over the volcanoes before the classic sunrise.',
        '800000.00',
        '2',
        '5',
        '22:00:00',
        '12:00:00',
        '2',
        'Area Parkir Jeep Cemoro Lawang, Ngadisari, Probolgo, Jawa Timur',
        'https://picsum.photos/seed/pkg-bromo-milkyway/800/600'
    ),
    (
        '52',
        '15',
        'Bromo Horse Riding Experience',
        'Explore the Sea of Sand on horseback after sunrise, riding up to the foot of the Bromo crater.',
        '700000.00',
        '2',
        '6',
        '06:00:00',
        '10:00:00',
        '5',
        'Area Parkir Jeep Cemoro Lawang, Ngadisari, Probolgo, Jawa Timur',
        'https://picsum.photos/seed/pkg-bromo-horse/800/600'
    ),
    (
        '53',
        '16',
        'Spiritual Cleansing & Rice Paddy Walk',
        'Combine a scenic walk through the rice paddies with a visit to the Tirta Empul temple for a traditional water purification ritual.',
        '550000.00',
        '1',
        '5',
        '08:00:00',
        '13:00:00',
        '2',
        'Meeting Point at Ubud Palace, Jl. Raya Ubud No.8, Ubud, Gianyar, Bali',
        'https://picsum.photos/seed/pkg-ubud-spiritual/800/600'
    ),
    (
        '54',
        '17',
        'Village Cycling & Temple Tour',
        'A unique tour combining a visit to Borobudur with a leisurely cycle through the local villages to see traditional life.',
        '650000.00',
        '2',
        '8',
        '07:00:00',
        '16:00:00',
        '5',
        'Titik Nol Kilometer Yogyakarta (Near Central Post Office), Yogyakarta',
        'https://picsum.photos/seed/pkg-temple-cycling/800/600'
    ),
    (
        '55',
        '18',
        'Ijen & Baluran National Park Combo',
        'A 2-day tour that combines the Ijen Blue Fire hike with a wildlife safari in Baluran National Park, the "Africa of Java".',
        '1800000.00',
        '2',
        '6',
        '23:00:00',
        '15:00:00',
        '5',
        'Pos Paltuding (Gerbang Masuk Kawah Ijen), Banyuwangi, Jawa Timur',
        'https://picsum.photos/seed/pkg-ijen-baluran/800/600'
    ),
    (
        '56',
        '19',
        'Wildlife Photography Trek',
        'A specialized, longer trek with a private ranger focused on finding the best opportunities to photograph Komodo dragons and other wildlife.',
        '750000.00',
        '1',
        '4',
        '08:00:00',
        '14:00:00',
        '2',
        'Pelabuhan Labuan Bajo, Manggarai Barat, NTT',
        'https://picsum.photos/seed/pkg-komodo-photo-trek/800/600'
    ),
    (
        '57',
        '20',
        'Batik Making & Silver Smithing Workshop',
        'An immersive cultural experience where you learn to create your own Batik and silver jewelry from local artisans.',
        '450000.00',
        '1',
        '6',
        '09:00:00',
        '15:00:00',
        '2',
        'Titik Nol Kilometer Yogyakarta (Near Central Post Office), Yogyakarta',
        'https://picsum.photos/seed/pkg-yogya-workshop/800/600'
    ),
    (
        '58',
        '1',
        'Family Fun Snorkel',
        'A shorter, relaxed snorkeling trip perfect for families with children, focusing on calm and shallow spots.',
        '500000.00',
        '2',
        '8',
        '10:00:00',
        '14:00:00',
        '4',
        'Pelabuhan Waisai, Raja Ampat, Papua Barat',
        'https://www.komodoluxury.com/wp-content/uploads/2024/02/21e0c704-187b-488c-8e8c-038c2fbf7114_11zon.webp'
    ),
    (
        '59',
        '2',
        'Sunset Snorkel & BBQ',
        'An afternoon snorkeling trip to Turtle Point, followed by a fresh seafood BBQ on the beach as the sun sets.',
        '350000.00',
        '4',
        '12',
        '15:00:00',
        '19:00:00',
        '4',
        'Public Harbour, Gili Trawangan, Lombok Utara, NTB',
        'https://www.komodoluxury.com/wp-content/uploads/2024/02/21e0c704-187b-488c-8e8c-038c2fbf7114_11zon.webp'
    ),
    (
        '60',
        '2',
        'Gili Meno Underwater Statues Trip',
        'A dedicated trip to the famous underwater statues at Gili Meno for incredible photo opportunities.',
        '200000.00',
        '2',
        '15',
        '11:00:00',
        '14:00:00',
        '1',
        'Public Harbour, Gili Trawangan, Lombok Utara, NTB',
        'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/60/e9/51/underwater-statue.jpg?w=1200&h=-1&s=1'
    ),
    (
        '61',
        '3',
        'Island Camping & Snorkel (3D2N)',
        'An adventurous 3-day, 2-night trip including island hopping, snorkeling, and camping on a remote island.',
        '1200000.00',
        '6',
        '12',
        '08:00:00',
        '16:00:00',
        '5',
        'Pelabuhan Kartini, Jepara, Jawa Tengah (Meeting point for ferry crossing)',
        'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/07/c3/f7/53/sea-adventure-excursions.jpg?w=1200&h=900&s=1'
    ),
    (
        '62',
        '4',
        'Discovery Scuba Dive',
        'Not certified? No problem. Try scuba diving for the first time with a professional PADI instructor in the calm waters of Bunaken.',
        '950000.00',
        '1',
        '4',
        '10:00:00',
        '13:00:00',
        '3',
        'Pelabuhan Calaca, Manado, Sulawesi Utara',
        'https://res.cloudinary.com/manawa/image/upload/f_auto,c_limit,w_3840,q_auto/articles/most-beautiful-spots-for-your-first-scuba-dive/61396758347_kwukov'
    ),
    (
        '63',
        '5',
        'East & West Penida Full Day Tour',
        'A comprehensive tour covering the best of both sides of Nusa Penida, including Kelingking Beach, Diamond Beach, and snorkeling spots.',
        '850000.00',
        '2',
        '6',
        '08:00:00',
        '17:00:00',
        '4',
        'Pelabuhan Toyapakeh, Nusa Penida, Bali',
        'https://picsum.photos/seed/pkg-east-west-penida/800/600'
    ),
    (
        '64',
        '8',
        'PADI Open Water Course',
        'Get your PADI Open Water certification in 3-4 days in the world-class diving environment of Komodo National Park.',
        '6500000.00',
        '1',
        '4',
        '08:00:00',
        '17:00:00',
        '3',
        'Pelabuhan Labuan Bajo, Manggarai Barat, NTT',
        'https://picsum.photos/seed/pkg-padi-owc/800/600'
    ),
    (
        '65',
        '10',
        'Sunrise Wreck Dive',
        'Be the first in the water with an early morning dive at the Liberty Wreck, enjoying serene conditions and seeing nocturnal creatures retreat.',
        '700000.00',
        '2',
        '6',
        '06:00:00',
        '08:00:00',
        '3',
        'Meeting Point at Liberty Dive Resort, Tulamben, Karangasem, Bali',
        'https://picsum.photos/seed/pkg-sunrise-wreck/800/600'
    ),
    (
        '66',
        '12',
        'Budget Liveaboard (Dorm)',
        'Explore Raja Ampat on a budget-friendly liveaboard with shared dormitory-style cabins.',
        '8000000.00',
        '8',
        '16',
        '11:00:00',
        '14:00:00',
        '1',
        'Pelabuhan Waisai, Raja Ampat, Papua Barat',
        'https://picsum.photos/seed/pkg-liveaboard-dorm/800/600'
    ),
    (
        '67',
        '12',
        'Luxury Liveaboard (Private Suite)',
        'Experience Raja Ampat in ultimate comfort on a luxury phinisi with a private suite and gourmet meals.',
        '25000000.00',
        '2',
        '6',
        '11:00:00',
        '14:00:00',
        '1',
        'Pelabuhan Waisai, Raja Ampat, Papua Barat',
        'https://picsum.photos/seed/pkg-liveaboard-luxury/800/600'
    ),
    (
        '68',
        '15',
        'Bromo Milky Way & Sunrise Tour',
        'A special tour for photographers, starting earlier to capture the Milky Way over the volcanoes before the classic sunrise.',
        '800000.00',
        '2',
        '5',
        '22:00:00',
        '12:00:00',
        '2',
        'Area Parkir Jeep Cemoro Lawang, Ngadisari, Probolinggo, Jawa Timur',
        'https://picsum.photos/seed/pkg-bromo-milkyway/800/600'
    ),
    (
        '69',
        '15',
        'Bromo Horse Riding Experience',
        'Explore the Sea of Sand on horseback after sunrise, riding up to the foot of the Bromo crater.',
        '700000.00',
        '2',
        '6',
        '06:00:00',
        '10:00:00',
        '5',
        'Area Parkir Jeep Cemoro Lawang, Ngadisari, Probolinggo, Jawa Timur',
        'https://picsum.photos/seed/pkg-bromo-horse/800/600'
    ),
    (
        '70',
        '16',
        'Spiritual Cleansing & Rice Paddy Walk',
        'Combine a scenic walk through the rice paddies with a visit to the Tirta Empul temple for a traditional water purification ritual.',
        '550000.00',
        '1',
        '5',
        '08:00:00',
        '13:00:00',
        '2',
        'Meeting Point at Ubud Palace, Jl. Raya Ubud No.8, Ubud, Gianyar, Bali',
        'https://picsum.photos/seed/pkg-ubud-spiritual/800/600'
    ),
    (
        '71',
        '17',
        'Village Cycling & Temple Tour',
        'A unique tour combining a visit to Borobudur with a leisurely cycle through the local villages to see traditional life.',
        '650000.00',
        '2',
        '8',
        '07:00:00',
        '16:00:00',
        '5',
        'Titik Nol Kilometer Yogyakarta (Near Central Post Office), Yogyakarta',
        'https://picsum.photos/seed/pkg-temple-cycling/800/600'
    ),
    (
        '72',
        '18',
        'Ijen & Baluran National Park Combo',
        'A 2-day tour that combines the Ijen Blue Fire hike with a wildlife safari in Baluran National Park, the "Africa of Java".',
        '1800000.00',
        '2',
        '6',
        '23:00:00',
        '15:00:00',
        '5',
        'Pos Paltuding (Gerbang Masuk Kawah Ijen), Banyuwangi, Jawa Timur',
        'https://picsum.photos/seed/pkg-ijen-baluran/800/600'
    ),
    (
        '73',
        '19',
        'Wildlife Photography Trek',
        'A specialized, longer trek with a private ranger focused on finding the best opportunities to photograph Komodo dragons and other wildlife.',
        '750000.00',
        '1',
        '4',
        '08:00:00',
        '14:00:00',
        '2',
        'Pelabuhan Labuan Bajo, Manggarai Barat, NTT',
        'https://picsum.photos/seed/pkg-komodo-photo-trek/800/600'
    ),
    (
        '74',
        '20',
        'Batik Making & Silver Smithing Workshop',
        'An immersive cultural experience where you learn to create your own Batik and silver jewelry from local artisans.',
        '450000.00',
        '1',
        '6',
        '09:00:00',
        '15:00:00',
        '2',
        'Titik Nol Kilometer Yogyakarta (Near Central Post Office), Yogyakarta',
        'https://picsum.photos/seed/pkg-yogya-workshop/800/600'
    ),
    (
        '76',
        '2',
        'Family Fun Snorkel',
        'A shorter, relaxed snorkeling trip perfect for families with children, focusing on calm and shallow spots.',
        '500000.00',
        '2',
        '8',
        '10:00:00',
        '14:00:00',
        '4',
        'Pelabuhan Waisai, Raja Ampat, Papua Barat',
        'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/26/60/e9/51/underwater-statue.jpg?w=1200&h=-1&s=1'
    ),
    (
        '77',
        '2',
        'Family Fun Snorkel',
        'A shorter, relaxed snorkeling trip perfect for families with children, focusing on calm and shallow spots.',
        '500000.00',
        '2',
        '8',
        '10:00:00',
        '14:00:00',
        '4',
        'Pelabuhan Waisai, Raja Ampat, Papua Barat',
        'https://www.komodoluxury.com/wp-content/uploads/2024/02/21e0c704-187b-488c-8e8c-038c2fbf7114_11zon.webp'
    ),
    (
        '78',
        '2',
        'Family Fun Snorkel',
        'A shorter, relaxed snorkeling trip perfect for families with children, focusing on calm and shallow spots.',
        '500000.00',
        '2',
        '8',
        '10:00:00',
        '14:00:00',
        '4',
        'Pelabuhan Waisai, Raja Ampat, Papua Barat',
        'https://www.komodoluxury.com/wp-content/uploads/2024/02/21e0c704-187b-488c-8e8c-038c2fbf7114_11zon.webp'
    );